//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transection
    {
        public int ID { get; set; }
        public int NoteID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
        public Nullable<bool> IsDownloaded { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual SellerNotes SellerNotes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
